// src/app/page.tsx
export default function HomePage() {
  return (
    <div className="text-white">
      <h1 className="text-3xl font-bold">aaaaaa to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>{" "}
      <h1 className="text-3xl font-bold">Welcome to Gfolio.jp</h1>
      <p className="mt-4">This is your homepage content.</p>
    </div>
  )
}
